[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/admin-login"
  to = "/admin-login.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin-login.html"
  status = 200

[[redirects]]
  from = "/api/submit-enquiry"
  to = "/.netlify/functions/submit-enquiry"
  status = 200

[[redirects]]
  from = "/api/admin-login"
  to = "/.netlify/functions/admin-login"
  status = 200

[[redirects]]
  from = "/api/enquiries"
  to = "/.netlify/functions/list-enquiries"
  status = 200

[[redirects]]
  from = "/api/enquiry"
  to = "/.netlify/functions/update-enquiry"
  status = 200
