[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/submit-enquiry"
  to = "/.netlify/functions/submit-enquiry"
  status = 200

[[redirects]]
  from = "/api/enquiries"
  to = "/.netlify/functions/list-enquiries"
  status = 200

[[redirects]]
  from = "/api/enquiry"
  to = "/.netlify/functions/update-enquiry"
  status = 200
